### PR TITLE
Android client beta launcher icon

### PR DESCRIPTION
**Pull request by AndyScherzinger**
see $subject, the launcher icon including the beta-tag for the beta app.

### CODE REVIEW

**Comment by jancborchardt** [comment]
The others are called »ico**n**-«, so if you fix that typo I’ll give you a plus one ;D

**Comment by AndyScherzinger** [comment]
@jancborchardt: Fixed :)

**Comment by tobiasKaminsky** [comment]
Not sure if this is the best way. I think a layer within SVG is better as we then have only one file...?

**Comment by AndyScherzinger** [comment]
It is a layer/text so we could then just delete the "standard" icon svg and rename the beta one.

What do you think @jancborchardt - I am fine either way. @tobiasKaminsky's approach seems neat lieke he already stated since we then only have to maintain one file :)

**Comment by jancborchardt** [comment]
BTW: Are the SVG icons part of the Android repo? If so, I think we don’t need to duplicate them here anyway. Only the base icons (the ones we already have) if people want to build apps for Nextcloud.

**Comment by AndyScherzinger** [comment]
The svg sources aren't part of the Android repo since they aren't part of the app itself. They app ships the generated png versions in the different resolutions.

**Comment by jancborchardt** [comment]
Ok. Let’s get it in then, we can change anything going forward. :)

**Pull request merged**
