### PR TITLE
Feature graphic for Talk app

### PR DESCRIPTION
**Pull request by jancborchardt**
Based on https://nextcloud.com/webrtc/ – please review @mario @jospoortvliet

### CODE REVIEW

**Comment by mario** [comment]
👍 

Fine for me.

**Review by jospoortvliet — APPROVED** [review]
Loving it.

**Comment by marinofaggiana** [comment]
beautiful !!

**Comment by tobiasKaminsky** [comment]
As talk about is not only about talking, but also about seeing the other person, wouldn't it be better if the person holds the device in her hand and another person is displayed on it? 
This way a new user can immediately imagine that it is "something like skype, but private".

**Comment by jospoortvliet** [comment]
@tobiasKaminsky you can go ask her 😄 

Seriously, sure, find a better pic... This is what we use on our website atm. Credit to Pexels, I think, and @MariusBluem found it.

**Pull request merged**
